# Autogenerated wrapper script for rocPRIM_jll for x86_64-linux-musl-cxx11
export rocprim

using hsa_rocr_jll
using ROCmCompilerSupport_jll
using ROCmOpenCLRuntime_jll
using HIP_jll
using rocm_cmake_jll
using rocminfo_jll
JLLWrappers.@generate_wrapper_header("rocPRIM")
JLLWrappers.@declare_file_product(rocprim)
function __init__()
    JLLWrappers.@generate_init_header(hsa_rocr_jll, ROCmCompilerSupport_jll, ROCmOpenCLRuntime_jll, HIP_jll, rocm_cmake_jll, rocminfo_jll)
    JLLWrappers.@init_file_product(
        rocprim,
        "rocprim",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
